### ISSUE TITLE
app error 377160

### ISSUE THREAD

**Issue by bananabull** [zerratar/fallout4-downgrader#1]
i ran the app and it gave me this error and a file to send 
[error.txt](https://github.com/zerratar/fallout4-downgrader/files/15172866/error.txt)

**Comment by zerratar** [comment]
You seem to be running an older version, please use the latest one and try again! The error occurs when the app seemingly login as anonymous instead of your steam credentials. Then it cant download the game files

**Comment by bananabull** [comment]
It work when I didn't select the down patch for the creation club
