### ISSUE TITLE
'timelast_update_corruption' not present in dictionary, erroring out on start

### ISSUE THREAD

**Issue by irkedIsaac** [zerratar/fallout4-downgrader#4]
![image](https://github.com/user-attachments/assets/19d5cc25-588c-46f5-8e4a-7f0f1c3961e3)
Recently did a full reinstall of FO4, trying to downgrade for compatibility, keep running into this error.  It says it put a full report in the error.txt file, but it looks exactly identical to its starting state to me.
[error.txt](https://github.com/user-attachments/files/18078244/error.txt)

**Comment by irkedIsaac** [comment]
I was able to get the downgrader to work (as far as, it launched appropriately and had a progress bar that told me it did its job), but my game just crashed at the main menu after that.  I will continue to troubleshoot on my own, but I'm assuming at this point that there's some issue on my end I don't know to look for.

**Comment by AClockworkApple** [comment]
> I was able to get the downgrader to work (as far as, it launched appropriately and had a progress bar that told me it did its job), but my game just crashed at the main menu after that. I will continue to troubleshoot on my own, but I'm assuming at this point that there's some issue on my end I don't know to look for.

hi, I'm having the same issue with timelast_update_corruption, my error file is identical to yours. How did you get it to this step?

**Comment by irkedIsaac** [comment]
> > I was able to get the downgrader to work (as far as, it launched appropriately and had a progress bar that told me it did its job), but my game just crashed at the main menu after that. I will continue to troubleshoot on my own, but I'm assuming at this point that there's some issue on my end I don't know to look for.
> 
> hi, I'm having the same issue with timelast_update_corruption, my error file is identical to yours. How did you get it to this step?

My bad - always gotta list your steps.  Moving the downgrader's files into Fallout's root folder (the folder that has Fallout4.exe in it) allowed it to run properly.  As far as I can tell, no issues downgrading the game anymore, and the crashing was due to a different, defunct mod.
